from .schema import (
    Base,
    Student,
    Document,
    Topic,
    Chunk,
    QuizAttempt,
    QuizQuestion,
    FlashcardEvent,
    Recommendation,
)
from .db import get_engine, get_session, init_db
from .crud import (
    get_or_create_student,
    list_students,
    create_document,
    replace_topics,
    get_topics_for_document,
    replace_chunks,
    get_chunks_for_document,
    get_chunk_counts_by_topic,
)

__all__ = [
    "Base",
    "Student",
    "Document",
    "Topic",
    "Chunk",
    "QuizAttempt",
    "QuizQuestion",
    "FlashcardEvent",
    "Recommendation",
    "get_engine",
    "get_session",
    "init_db",
    "get_or_create_student",
    "list_students",
    "create_document",
    "replace_topics",
    "get_topics_for_document",
    "replace_chunks",
    "get_chunks_for_document",
    "get_chunk_counts_by_topic",
]
